M48
; DRILL file {KiCad (6.0.1)} date Tue Feb  8 14:36:32 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-08T14:36:32+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X74.371Y-81.331
X80.924Y-132.842
X148.742Y-133.096
X149.708Y-87.986
T0
M30
